batch:
  exit_on_error: true
embedding:
  chinese_model: jina-zh
  default_model: mixbread
hardware:
  device: mps
  use_cuda: auto
  use_mps: auto
haystack:
  document_store: memory
  retriever:
    top_k: 5
language:
  default: en
  supported:
  - en
  - zh
llama_index:
  service_context:
    chunk_overlap: 20
    chunk_size: 1024
llm:
  default_model: l3:latest
  ollama_host: http://localhost
  ollama_port: 11434
  source: ollama
query:
  k_value: 5
storage:
  vector_store: llama_index
system:
  batch_mode: true
  debug: false
  debug_level: 'off'
  hpc_mode: true
  output_format: txt
topic:
  use_originals: true
workspace:
  default: default
